Update services host urls
PlayNetwork/playnetwork-sdk-nodejs pull request #111
Opened 2021-06-09 19:48 UTC by jcarva

[BMS-759 Ticket](https://jira.touchtunes.com/browse/BMS-759)

- Create host constant file
- Update URLs
- Bump to v2.2.9

2021-06-09 20:19 UTC, jcarva commented
For  campaign  and location-relationships API's hosts we have
```
CAMPAIGN_API: 'campaign-api.apps.playnetwork.com',
LOCATION_RELATIONSHIPS_API: 'location-relationships-api.apps.playnetwork.com',
```
, but it seems that they don't work.

I tried some Campaign API alias from MOJI API in Prod,
```
"APP_ALIAS": "master-campaign-api.apps.playnetwork.com,master-campaign-api-internal.apps.playnetwork.com,master-campaignapi.scaffold-workers-ext-main-us.m.cld.octavelive.com",
```
, but still the same result:

Same for Location Relationships API, I tried another alias from the [Wiki](https://wiki.touchtunes.com/display/TSP/Postponed+items#Postponeditems-Repositorylocation-relationships-api).

2021-06-09 20:22 UTC, jcarva commented
About Asset, Station, and Brand API’s hosts, they only work with the below URLs, I couldn’t make them shorter or remove “paths”.
```
ASSET_API: 'master-assetapi.scaffold-workers-ext-main-us.m.cld.octavelive.com',
STATION_API: 'master-stationapi.scaffold-workers-ext-main-us.m.cld.octavelive.com',
BRAND_API: 'master-brand-api.apps.playnetwork.com'
```

2021-06-10 15:29 UTC, gcerrott commented
> About Asset, Station, and Brand API’s hosts, they only work with the below URLs, I couldn’t make them shorter or use others domains/subdomains. Maybe we can add few alias.
> 
> ```
> ASSET_API: 'master-assetapi.scaffold-workers-ext-main-us.m.cld.octavelive.com',
> STATION_API: 'master-stationapi.scaffold-workers-ext-main-us.m.cld.octavelive.com',
> BRAND_API: 'master-brand-api.apps.playnetwork.com'
> ```

I don't get this comment because I get response for all the following:
https://master-asset-api.apps.playnetwork.com/v1/version
https://master-station-api.apps.playnetwork.com/v3/version
https://master-brand-api.apps.playnetwork.com/version

2021-06-14 17:00 UTC, gcerrott requested changes

2021-06-14 17:00 UTC, gcerrott commented on lib/hosts.js
> +    STATION_API: 'master-stationapi.scaffold-workers-ext-main-us.m.cld.octavelive.com',
master-station-api.apps.playnetwork.com

2021-06-14 17:00 UTC, gcerrott commented on lib/hosts.js
> +    ASSET_API: 'master-assetapi.scaffold-workers-ext-main-us.m.cld.octavelive.com',
master-asset-api.apps.playnetwork.com

2021-06-15 14:04 UTC, jcarva commented
> > About Asset, Station, and Brand API’s hosts, they only work with the below URLs, I couldn’t make them shorter or use others domains/subdomains. Maybe we can add few alias.
> > ```
> > ASSET_API: 'master-assetapi.scaffold-workers-ext-main-us.m.cld.octavelive.com',
> > STATION_API: 'master-stationapi.scaffold-workers-ext-main-us.m.cld.octavelive.com',
> > BRAND_API: 'master-brand-api.apps.playnetwork.com'
> > ```
> 
> I don't get this comment because I get response for all the following:
> https://master-asset-api.apps.playnetwork.com/v1/version
> https://master-station-api.apps.playnetwork.com/v3/version
> https://master-brand-api.apps.playnetwork.com/version


Sorry, I should have been explained better, what I wanted was a shorter version of the initial hosts urls, and you already gave me them in the comments, just updated it, thanks :)

2021-06-17 15:01 UTC, gcerrott approved these changes

2021-06-17 18:23 UTC, benjamin-morin approved these changes
Looks good!

2021-06-21 15:26 UTC, Mig-OG approved these changes
This repository is public and I must ask: Do we really want to have a comprehensive list of every production API URLs?

2021-06-21 15:26 UTC, Mig-OG commented on history.md
> +# v2.2.9 - 2020/06/09
You probably intend to write: `2021/06/09`.
In any case, we decided to remove the `history.md` file from our repos since we can refer to git history. I think this one should be removed to.

2021-06-21 21:13 UTC, merged