story107 add player service communication; add unit tests
PlayNetwork/playnetwork-sdk-nodejs pull request #49
Opened 2017-07-24 22:00 UTC by cmerchant

minimal changes required

2017-07-24 22:41 UTC, brozeph requested changes

2017-07-24 22:41 UTC, brozeph commented on lib/index.js
> +		self.playersvc = new PlayerServiceProxy(options.playersvc, key.ensureAuthHeaders);
This may be a bit pedantic... can we consider naming this to `realtime` (i.e. `self.realtime`)?

2017-07-24 22:41 UTC, brozeph commented on lib/playersvc.js
> +				   '?clientId=',
There appear to be 3 or 4 extraneous spaces after the tab indents here... consider replacing these extraneous spaces with a tab...

```javascript
			url = [
					DEFAULT_URL,
					'?clientId=',
					/* abbreviated */
```

2017-07-24 22:41 UTC, brozeph commented on lib/playersvc.js
> +			})
Missing a semi-colon

2017-07-24 22:41 UTC, brozeph commented on lib/playersvc.js
> +		})
Missing a semi-colon

2017-07-24 22:41 UTC, brozeph commented on lib/playersvc.js
> +	}
Missing a semi-colon

2017-07-24 22:41 UTC, brozeph commented on lib/playersvc.js
> +	}
Missing a semi-colon

2017-07-24 22:41 UTC, brozeph commented on lib/playersvc.js
> +	}
Missing a semi-colon

2017-07-24 22:41 UTC, brozeph commented on lib/playersvc.js
> +}
Missing a semi-colon

2017-07-25 01:04 UTC, cmerchant commented on lib/index.js
> +		self.playersvc = new PlayerServiceProxy(options.playersvc, key.ensureAuthHeaders);
sure

2017-07-25 01:05 UTC, cmerchant commented on lib/playersvc.js
> +				   '?clientId=',
ok

2017-07-25 17:58 UTC, cmerchant commented on lib/playersvc.js
> +}
ok

2017-07-25 17:58 UTC, cmerchant commented on lib/playersvc.js
> +	}
ok

2017-07-25 17:58 UTC, cmerchant commented on lib/playersvc.js
> +			})
ok

2017-07-25 17:59 UTC, cmerchant commented on lib/playersvc.js
> +		})
ok

2017-07-25 17:59 UTC, cmerchant commented on lib/playersvc.js
> +	}
ok

2017-07-25 19:19 UTC, cmerchant commented on lib/index.js
> +		self.playersvc = new PlayerServiceProxy(options.playersvc, key.ensureAuthHeaders);
I'm not actually sure about that because the options are specifically for the player service like url, client id, shared secret etc. What do you think?

2017-07-25 19:21 UTC, cmerchant commented on lib/playersvc.js
> +				   '?clientId=',
Also, here I think we should be using settings.host and not DEFAULT_URL

2017-07-25 20:25 UTC, cmerchant commented
need implement a few more events for connection errors and reconnections

2017-07-26 17:49 UTC, cmerchant commented
I think everything is addressed

2017-07-26 19:49 UTC, sanakanchha commented on lib/playersvc.js
> +			throw new Error('Unable to disconnect, no socket connection')
missed a semi colon :)

2017-07-26 19:50 UTC, deepakdahal commented on lib/playersvc.js
> +			throw new Error('Unable to emit, no socket connection')
missed a semi colon

2017-07-26 19:53 UTC, deepakdahal commented
should this be going into develop or the latest version?

2017-07-26 20:08 UTC, deepakdahal commented on readme.md
> +      host : 'https://player-svc.apps.playnetwork.com'
remove https if it can be accessed over http as well. Plus looks like the convention is not to add the protocol as a part of the url.

2017-07-26 20:21 UTC, deepakdahal commented on test/Mocks/mockSocketIOClient.js
> +const CONNECT_DELAY = 1000;
CONNECT_DELAY_IN_MILLISECONDS over CONNECT_DELAY would make it more clear.

2017-07-26 20:39 UTC, cmerchant commented on lib/playersvc.js
> +			throw new Error('Unable to emit, no socket connection')
Not you too :) Ok, I will add it.

2017-07-26 20:40 UTC, cmerchant commented on lib/playersvc.js
> +			throw new Error('Unable to disconnect, no socket connection')
ok

2017-07-26 20:41 UTC, cmerchant commented on readme.md
> +      host : 'https://player-svc.apps.playnetwork.com'
No, we don't support that anymore, just https. I guess I can make it consistent though

2017-07-26 20:42 UTC, cmerchant commented on test/Mocks/mockSocketIOClient.js
> +const CONNECT_DELAY = 1000;
ok

2017-07-26 21:06 UTC, cmerchant commented on test/Mocks/mockSocketIOClient.js
> +const CONNECT_DELAY = 1000;
That constant is not used, I will remove it!

2017-07-26 21:07 UTC, cmerchant commented
@deepakdahal develop is the latest at 1.1.12. The other branch is 1.1.9

2017-07-30 04:27 UTC, brozeph requested changes

2017-07-30 04:27 UTC, brozeph commented on test/Mocks/mockSocketIOClient.js
> +const proxyquire = require('proxyquire');
Alphabetize ;)

2017-07-30 04:27 UTC, brozeph commented on test/Mocks/mockSocketIOClient.js
> +			})
Missing semi-colon

2017-07-30 04:27 UTC, brozeph commented on test/Mocks/mockSocketIOClient.js
> +	}
Missing semi-colon

2017-07-30 04:27 UTC, brozeph commented on test/lib/playersvc.js
> +	})
Missing semi-colon

2017-07-30 04:27 UTC, brozeph commented on test/lib/playersvc.js
> +			})
Missing semi-colon

2017-07-30 04:27 UTC, brozeph commented on test/lib/playersvc.js
> +				err.message.should.equal('Unable to disconnect, no socket connection');
Nicely tested here

2017-08-09 17:45 UTC, cmerchant commented on test/lib/playersvc.js
> +	})
ok

2017-08-09 17:45 UTC, cmerchant commented on test/lib/playersvc.js
> +			})
ok

2017-08-09 17:45 UTC, cmerchant commented on test/lib/playersvc.js
> +				err.message.should.equal('Unable to disconnect, no socket connection');
Thanks!

2017-08-09 17:46 UTC, cmerchant commented on test/Mocks/mockSocketIOClient.js
> +	}
ok

2017-08-09 17:46 UTC, cmerchant commented on test/Mocks/mockSocketIOClient.js
> +			})
ok

2017-08-09 17:46 UTC, cmerchant commented on test/Mocks/mockSocketIOClient.js
> +const proxyquire = require('proxyquire');
ok

2017-08-09 17:48 UTC, cmerchant commented
everything addressed. Ready for round 3 :)

2017-08-10 01:03 UTC, brozeph requested changes

2017-08-10 01:03 UTC, brozeph commented on lib/index.js
> +		self.playersvc = new PlayerServiceProxy(options.playersvc, key.ensureAuthHeaders);
More specifically, I don't like the usage of `svc` in the name because it's not consistent with any of the other sub-modules for the API. The consistency is a key element here especially considering the nature of the SDK being open source. I'm OK with other names... perhaps just `player`?

2017-08-10 01:03 UTC, brozeph commented on lib/index.js
> +			playerservce : self.playersvc.settings(),
This is misspelled here (missing an `i`)... but this should be named accordingly with the changes requested from the comment above.

2017-08-10 01:03 UTC, brozeph commented on lib/playersvc.js
> +			socket.on('connect_error', (err) => {
Kill this, just use `error` and add a field to the `Error` object that is passed to help qualify if needed. As high level guidance for this, think of the work you do in the SDK as needed to support only what we want to build up front in the Z8 - this does not need to be (and probably should not be) exhaustively backwards compatible with the X5.

2017-08-10 01:03 UTC, brozeph commented on lib/playersvc.js
> +			socket.on('reconnect_error', (err) => {
Kill this, and use the `error` event

2017-08-10 01:03 UTC, brozeph commented on lib/playersvc.js
> +			socket.on('reconnect_failed', () => {
On the whole, reading through these events, there are a few things I'm not liking up front:
* `playerRpc` vs. `reconnect_failed` - one event uses camel case and another uses underscore characters... this inconsistency is confusing
* consider renaming `playerRpc` to simply `message` (i.e. `playnetwork.realtime.on('message', handler);`)
* the documentation calls out `connect_timeout` but this isn't actually implemented in the code
* `reconnect_failed` seems redundant in the event there is an error because the failure to connect is implicitly understood
* is it really necessary to have both `reconnect` and `connect`? What happens during a reconnect... does only the `reconnect` fire and not the `connect`? Would a client using the SDK really need to understand this nuance at all?
* Is it really necessary to have both `reconnect_attempt` and `reconnecting`?

2017-08-10 01:03 UTC, brozeph commented on readme.md
> +* Event: 'connect'
I recommend creating a sub-heading below the methods (`connect`, `disconnect` and `emit`) that covers the Events specifically instead of putting them into the `connect` documentation.

2017-08-10 17:44 UTC, cmerchant commented on lib/index.js
> +		self.playersvc = new PlayerServiceProxy(options.playersvc, key.ensureAuthHeaders);
Ok, let me think about it. Maybe player is ok.

2017-08-10 17:44 UTC, cmerchant commented on lib/index.js
> +			playerservce : self.playersvc.settings(),
yep

2017-08-10 17:46 UTC, cmerchant commented on lib/playersvc.js
> +			socket.on('connect_error', (err) => {
yeah, that's a good idea. This particular implementation is just based on what the socket io client is providing for events. Per last night's discussion I think it will make the sdk a bit easier/cleaner.

2017-08-10 17:46 UTC, cmerchant commented on lib/playersvc.js
> +			socket.on('reconnect_error', (err) => {
yes

2017-08-10 17:47 UTC, cmerchant commented on lib/playersvc.js
> +			socket.on('reconnect_failed', () => {
I will try to combine some of them :) It was just originally based on a 1-1 coorespondance to the underlying socket io lib

2017-08-10 17:47 UTC, cmerchant commented on readme.md
> +* Event: 'connect'
ok

2017-08-14 20:48 UTC, brozeph reviewed
This is getting tight - I really like where this is headed. For the underlying `socket.io-client` library, did we capture all potential `error` event contributors and rewire them to `error`?

2017-08-14 20:48 UTC, brozeph commented on lib/player.js
> +			socket.on('reconnect', (attempt) => {
Nice pattern here

2017-08-14 20:48 UTC, brozeph commented on lib/player.js
> +			socket.on('playerRpc', (data) => {
How do you feel about naming this `message` instead of `playerRpc`?

2017-08-14 20:51 UTC, cmerchant commented
I think I rewired all 3 error events to just error.

2017-08-14 20:55 UTC, cmerchant commented on lib/player.js
> +			socket.on('playerRpc', (data) => {
I was trying to be consistent with the actual player service. It uses that. I see the benefits of changing it in that if we ever do something other than json rpc we would not have to change the name

2017-08-14 20:55 UTC, cmerchant commented on lib/player.js
> +			socket.on('reconnect', (attempt) => {
thanks

2017-08-14 21:01 UTC, cmerchant commented on lib/player.js
> +			socket.on('playerRpc', (data) => {
We would still need the socket.on('playerRpc' part but we could translate that to message for the subscriber, for example:

			socket.on('playerRpc', (data) => {
				socketEventSubscriber.emit('message', data);
			});

2017-08-15 13:29 UTC, merged