Add support for activation and apps route, fix unit tests
PlayNetwork/playnetwork-sdk-nodejs pull request #53
Opened 2017-10-19 20:58 UTC by cmerchant

2017-10-23 14:46 UTC, deepakdahal commented on lib/provision.js
> +    let exec = co(function *() {
why generators? can't we achieve this using async/await?

2017-10-23 14:46 UTC, deepakdahal commented on lib/provision.js
> +				query : options,
extra indentation here

2017-10-23 14:46 UTC, deepakdahal commented on lib/provision.js
> +				rawStream : true
extra tabbing here

2017-10-23 14:46 UTC, deepakdahal commented on lib/provision.js
> +				rawStream : true
what is a rawStream? Always set to true?

2017-10-23 17:56 UTC, cmerchant commented on lib/provision.js
> +    let exec = co(function *() {
I think it is still based on node 6 and not being transpiled. It is how the entire library is implemented.

2017-10-23 17:58 UTC, cmerchant commented on lib/provision.js
> +				rawStream : true
It's the same as the content library. It is necessary in order to get a stream to the file contents.

2017-10-23 17:59 UTC, cmerchant commented on lib/provision.js
> +				rawStream : true
Looks like I used spaces except on this line :) I will convert it to tabs.

2017-10-23 17:59 UTC, cmerchant commented on lib/provision.js
> +				query : options,
I was inconsistent with tabs and spaces. I will fix it.

2017-10-23 19:30 UTC, rmomii commented
@cmerchant looks really clean! I only had some feedback for the validation/callbacks. Otherwise, it looks great.

2017-10-23 19:31 UTC, rmomii requested changes

2017-10-23 19:31 UTC, rmomii commented on lib/provision.js
> +		let exec = co(function *() {
For both `getApplicationStream` and `getClientCredentialStream`:
+ I would add some validation here for the `options` and `deviceId` (see `getOrder` function below where it handles non-specified input params)) 
+ We are missing callbacks in both functions (`getOrder` can also be used as an example for this). We have been returning `validation.promiseOrCallback()` on all of our functions (see `lib/validation.js`) to ensure we return the appropriate response when dealing with callbacks and promises.

2017-10-23 20:04 UTC, brozeph requested changes

2017-10-23 20:04 UTC, brozeph commented on lib/provision.js
> +	self.getClientCredentialsStream = (deviceId, options) => {
Are we returning a file stream here (i.e. binary data) or is this really an API call to get an object that represents the credentials? I would strongly recommend that this should be the latter and I would also argue that we don't want to document this method in the `readme.md` as it's not something a typical 3rd party consumer of our APIs would use. Additionally, we should consider how this method is named (see above comment).

2017-10-23 20:04 UTC, brozeph commented on lib/provision.js
> +	self.getApplicationsStream = (options) => {
Are we returning an actual file stream here (i.e. the Docker container itself or some .tar.gz)? If not, we should consider a different name for this method because it infers the response is a stream object... additionally, if it is returning a stream of the HTTP response from an API call, we should encapsulate the response so that it is an object or something easy for the consumer to work with as opposed to a stream where the response data has to be parsed, etc.

2017-10-23 20:12 UTC, cmerchant commented on lib/provision.js
> +		let exec = co(function *() {
ok, do we really need a callback or would returning a promise be sufficient?

2017-10-23 20:20 UTC, cmerchant commented on lib/provision.js
> +		let exec = co(function *() {
I guess for consistency with the other modules, we can do the callback.

2017-10-23 20:22 UTC, cmerchant commented on lib/provision.js
> +	self.getClientCredentialsStream = (deviceId, options) => {
It does return a file stream and then the activation app reads the stream. Utlimately the stream is a JSON object when read. Is it possible to just return directly the JSON object instead of reading the stream? If so, I can implement it that way.

2017-10-23 20:24 UTC, cmerchant commented on lib/provision.js
> +	self.getApplicationsStream = (options) => {
It will be a yml file. Perhaps I should leave this out until Garris and Deepak are ready and have finalized the return value.

2017-10-23 21:04 UTC, cmerchant commented on lib/provision.js
> +	self.getClientCredentialsStream = (deviceId, options) => {
Yep, I can just return the body of the html response which is the json object representing the credentials. This makes the code in the activation app simpler. Thanks for the suggestion!

2017-10-23 21:10 UTC, cmerchant commented
@rmomii @brozeph I think I covered everything mentioned here. I reverted the readme and removed the getApplicationsStream. Deepak and Garris can work on that when ready.

2017-10-24 01:22 UTC, rmomii commented on lib/provision.js
the only other things is the validation for the `deviceId` but other than that it looks good!

2017-10-24 01:35 UTC, cmerchant commented on lib/provision.js
@rmomii the validation is there on line 148, just scroll down a bit. I copied how it was done in the other methods.

2017-10-24 01:45 UTC, rmomii commented on lib/provision.js
ahh my bad !! ok, approved!

2017-10-24 01:45 UTC, rmomii approved these changes

2017-10-24 17:01 UTC, merged