sdk#284 : add updater app routes plus tests
PlayNetwork/playnetwork-sdk-nodejs pull request #54
Opened 2017-10-30 18:53 UTC by deepakdahal

- add the bridge for updater app to be able to talk to provision api to check for updates and download yml files when needed

2017-11-06 21:40 UTC, deepakdahal commented
@brozeph, @cmerchant , @rmomii need some traction on this PR.

2017-11-07 20:03 UTC, cmerchant requested changes

2017-11-07 20:03 UTC, cmerchant commented on lib/provision.js
> +	self.getUpdate = (options, callback) => {
maybe rename to getApplications?

2017-11-07 20:03 UTC, cmerchant commented on lib/provision.js
> +	self.checkUpdate = (options, callback) => {
maybe rename to getAppsSignature

2017-11-07 20:28 UTC, rmomii commented on lib/provision.js
> +	self.checkUpdate = (options, callback) => {
I agree with craig -- rename to make a bit more specific

2017-11-07 20:28 UTC, rmomii commented on lib/provision.js
> +	self.getUpdate = (options, callback) => {
also, alphabetize functions after you rename! makes it easier to read

2017-11-07 20:31 UTC, rmomii commented
aside from craig's comments, looks good to me!

2017-11-08 15:50 UTC, brozeph requested changes

2017-11-08 15:50 UTC, brozeph commented on lib/provision.js
> +	self.checkUpdate = (options, callback) => {
Because this uses a `HEAD` request, I do like the naming as it is (`checkUpdate`)... this is consistent with `checkAsset` and `checkLegacyAsset` in the `content` sub-module.

2017-11-08 15:50 UTC, brozeph commented on lib/provision.js
> +	self.getUpdate = (options, callback) => {
if `/v2/applications` returns the applications specifically for the caller, perhaps we could name this `allApplications` to be consistent with naming used elsewhere in the SDK? (i.e. a `GET` to `/v0/somethings` is referred to as `allSomethings` where is a `GET` to `/v0/somethings/:somethingId` is referred to as `getSomething`.

2017-11-08 15:50 UTC, brozeph commented on lib/provision.js
> +	self.checkUpdate = (options, callback) => {
Also, is there a header that is returned when performing a `HEAD` request, or is the general idea here just to determine if this returns a `404`? If it's the latter, this method may not be necessary.

2017-11-08 15:50 UTC, brozeph commented on lib/provision.js
> +		return validation.promiseOrCallback(exec, callback);
For consumers of the SDK, would it be easier to actually process the stream and return something like a text output from this? 

Here's an example only - may not be correct, but as an idea to illustrate the point:

```javascript
let 
	headers = ensureAuthHeaders(options),
	stream = yield req.head( /* ... */ ),
	yaml = '';

return yield new Promise((resolve, reject) => {
	stream.on('data', (chunk) => (yaml += chunk));
	stream.on('end', () => (resolve(yaml));
	stream.on('error', reject);
});
```

2017-11-08 16:06 UTC, deepakdahal commented on lib/provision.js
> +	self.checkUpdate = (options, callback) => {
yes, a header is returned

2017-11-08 16:31 UTC, deepakdahal commented on lib/provision.js
> +	self.getUpdate = (options, callback) => {
okay, renaming this to allApplications

2017-11-09 15:22 UTC, deepakdahal commented on lib/provision.js
> +		return validation.promiseOrCallback(exec, callback);
sure I could make the change though the updater app has already been coded with consuming raw stream data.

2017-11-10 16:36 UTC, merged

2017-11-10 16:36 UTC, deepakdahal commented on lib/provision.js
> +		return validation.promiseOrCallback(exec, callback);
After discussing with Josh, we will keep this as raw stream as it is a hyper specialized case where we download the yaml and not JSON doc as other apis