V1.3.8 handle exception gracefully when a url doesn't resolve
PlayNetwork/playnetwork-sdk-nodejs pull request #63
Opened 2018-07-03 15:37 UTC by deepakdahal

Whenever a url doesn't resolve(due to network connectivity, incorrect url etc.), this lib throws an exception which wasn't handled gracefully.

2018-07-03 16:07 UTC, brozeph requested changes

2018-07-03 16:07 UTC, brozeph commented on lib/key.js
> +			return err.message;
This should be `return reject(err);`

2018-07-03 16:07 UTC, brozeph commented on test/lib/key.js
> -		it('should require clientId', (done) => {
If you remove the callback here but don't use `async` and `await` then the test won't run / complete the way it is intended to. If you'd like to head this route, the better step is to upgrade the `mocha` dependency, but this is a relatively in-depth task because there may need to be a lot more adjustments made in the SDK to support this.

2018-07-03 16:07 UTC, brozeph commented on test/lib/key.js
> -		it('should require secret', (done) => {
Same comment as above - this is not having the intended effect, the test is not running.

2018-07-03 16:20 UTC, rmomii commented on lib/key.js
> +			return err.message;
Shouldn't it be `return Promise.reject(err)`? I think `reject` is outside of the scope..

2018-07-03 16:21 UTC, brozeph commented on lib/key.js
> +			return err.message;
Yes, good catch!

2018-07-03 16:38 UTC, deepakdahal commented on lib/key.js
> +			return err.message;
I had it this way initially. Unfortunately, the unhandled promise rejection didn't get fixed killing the realtime app.

2018-07-03 16:41 UTC, deepakdahal commented on lib/key.js
> +			return err.message;
However,  I could either go with  Promise.resolve(err); or just the way it is in order to send a graceful message to the realtime app.

2018-07-03 16:45 UTC, brozeph commented on lib/key.js
> +			return err.message;
This would be a bad idea - the intended effect here is to indicate that an error has occurred and processing can't complete. For any other consumer of the SDK, to receive a properly resolved promise with an object response that does not match expectations would be really bad. This seems to point at something that is not working as expected in the code that is consuming the SDK... especially if you build a unit test to validate this.

2018-07-03 17:11 UTC, cmerchant commented on lib/key.js
> +			return err.message;
Can you modify the code in player.js to handle the reject instead of changing the return type of the method?

2018-07-03 17:12 UTC, deepakdahal commented on lib/key.js
> +			return err.message;
okay, actually it is the player.js in the sdk calling the key.js for authorization before a socket connection to be established. Should it be handled different if it is events we are listening to?
Here is the code in player.js calling the key.js. 

self.connect = (socketEventSubscriber) => {
		co(function *() {
			let
				authHeaders = yield ensureAuthHeaders(),
*************
*************
socket.on('error', (err) => {
				socketEventSubscriber.emit('error', err);
			});

Realtime just waits on the response this event/s receive.

2018-07-03 17:14 UTC, cmerchant commented on lib/key.js
> +			return err.message;
maybe add a catch for the yield ensureAuthHeaders call here and then if it catches the error emit the error?

2018-07-03 17:17 UTC, brozeph commented on lib/key.js
> +			return err.message;
if `ensureAuthHeaders` fails, the `co` should bubble the exception as a rejected Promise. However, notice that the `co` function is not being returned... add a `return` statement before `co` and this will probably help.

2018-07-03 17:18 UTC, brozeph commented on lib/key.js
> +			return err.message;
or rewrite a bit...

```
self.connect = (socketEventSubscriber) => (co(function *() {
// teh codez herr
});
```

2018-07-03 18:45 UTC, deepakdahal commented on lib/key.js
> +			return err.message;
okay, working on a fix. on the player.js file, thank you.
We found an issue with socket-io-client where it doesn't try to reconnect if failed during during authorization. Craig is looking into whether upgrading socket-io-client is a solution.

2018-07-03 18:47 UTC, deepakdahal commented on lib/key.js
> +			return err.message;
Here is the link: https://stackoverflow.com/questions/24390482/socket-io-failing-authorization-does-not-retry-to-reconnect

2018-07-05 17:58 UTC, cmerchant commented on lib/player.js
> +			if(authHeaders != null) {
This condition will always be true because you are always returning an error from the call to ensureAuthHeaders or it actually returns headers

2018-07-05 17:59 UTC, cmerchant commented on lib/player.js
> +			if(authHeaders != null) {
also, you would never try to connect at all meaning the reconnect logic won't be hit at all

2018-07-05 18:00 UTC, cmerchant commented on lib/player.js
> +					socket.disconnect();
indentation is off here

2018-07-05 22:04 UTC, deepakdahal commented
@brozeph , @cmerchant , @rmomii  the same PR with new changes if you could take a look would be great.

2018-07-05 22:12 UTC, brozeph commented on lib/player.js
> +		if (validation.isEmpty(socketEventSubscriber) || !socketEventSubscriber.emit) {
This works, but we're really not checking to see if the socketEventSubscriber is an EventEmitter per se, only that it has a property named `emit` and not even that it's a function. Might be worthwhile thinking through how to validate if the `emit` is a function as well.

```javascript
if ([
  validation.isEmpty(socketEventSubscriber),
  validation.isEmpty(socketEventSubscriber.emit),
  typeof socketEventSubscriber.emit !== 'function'
].some((val) => val)) {
  throw new Error('socketEventSubscriber must be an instance of event.EventEmitter');
}
```

2018-07-05 22:12 UTC, brozeph commented on lib/player.js
> +		query = ['clientId=', clientId, '&', 'token=', authToken].join('');
```javascript
query = ['clientId=', clientId, '&token=', authToken].join('');
```

2018-07-05 22:12 UTC, brozeph commented on lib/player.js
> +				'headerReset' : false,
How is `headerReset` used by clients... there is also an `isReconnect` that's present on other `connection` objects emitted and this field isn't consistent with those. Is this by design and is this well understood by the consuming code? Seems like this could lead to some confusion...

2018-07-05 22:15 UTC, cmerchant commented on lib/player.js
> +		url = [protocol, '://', options.host || settings.host].join('');
Will it ever be possible that options.host and settings.host are both defined. What would happen in this case in forming the url?

2018-07-05 22:20 UTC, cmerchant commented on lib/player.js
> +				'headerReset' : false,
it is used by realtime app. It should be documented in the sdk readme

2018-07-05 22:20 UTC, brozeph commented on lib/player.js
> +		url = [protocol, '://', options.host || settings.host].join('');
`options.host` should take precedent over `settings.host` if this were to be the case... the idea here is that you configure the SDK at initialization, but you have the ability to override on a per call basis for über flexibility

2018-07-05 22:22 UTC, cmerchant commented on lib/player.js
> +				'headerReset' : false,
the main reason is that we are emiting a connected event for both connect and reconnect. It lets the consumer be aware of this situation. In the realtime app case, it is used for logging

2018-07-05 22:27 UTC, sanakanchha commented on lib/player.js
> +		if (validation.isEmpty(socketEventSubscriber) || !socketEventSubscriber.emit) {
taken care of

2018-07-05 22:28 UTC, cmerchant commented on lib/player.js
> +				'headerReset' : false,
I think you can get rid of headerReset. That seems to be a relic of an earlier implementation. @deepakdahal please double check that before removing.

2018-07-05 22:28 UTC, sanakanchha commented on lib/player.js
> +		query = ['clientId=', clientId, '&', 'token=', authToken].join('');
taken care of

2018-07-05 22:51 UTC, deepakdahal commented on lib/player.js
> +				'headerReset' : false,
@cmerchant looks like we have tests added for headerReset https://github.com/PlayNetwork/playnetwork-sdk-nodejs/blob/develop/test/lib/player.js#L216

2018-07-05 23:20 UTC, cmerchant commented
I thought there was some co function that needed a return value. Where is that?

2018-07-06 15:41 UTC, brozeph requested changes
Getting close!

2018-07-06 15:41 UTC, brozeph commented on lib/player.js
> +			].some((val) => val)) {
de-indent the line 😺

2018-07-06 15:41 UTC, brozeph commented on lib/player.js
> +				'headerReset' : false,
The tests are there, but do we actually use it anywhere? If not, we should remove it and the tests...

2018-07-06 17:27 UTC, sanakanchha commented on lib/player.js
> +			].some((val) => val)) {
taken care of

2018-07-06 17:27 UTC, sanakanchha commented on lib/player.js
> +				'headerReset' : false,
okay, headerReset has been removed both from test and code

2018-07-06 17:38 UTC, deepakdahal commented
@brozeph @cmerchant I should have covered everything :)

2018-07-06 17:44 UTC, cmerchant commented
Looks good to me

2018-07-06 17:47 UTC, merged