Fixes connection pool bug
PlayNetwork/playnetwork-sdk-nodejs pull request #86
Opened 2019-03-01 19:16 UTC by icalderontt

Now it makes use of a connection pool when necessary which should boost
requests speed.

2019-03-01 19:22 UTC, icalderontt commented
Here's the related ticket: http://jira.touchtunes.com/browse/BMS-8

2019-03-01 19:23 UTC, brozeph commented on .nvmrc
> +8.15.0
I have philosophical reservations around checking-in developer specific environment artifacts like this `.nvmrc' file. While it is not likely to cause issues, many devs use `tj/n` or even Homebrew (uck...) to manage their Node versions and this file would be vestigial. It's not like checking in a VS Code prefs file... perhaps we should add the .nvmrc to the .gitignore?

2019-03-01 19:23 UTC, brozeph commented on lib/utils.js
> +  }
Generally looks like there there are mixed tabs and spaces in the file (see lines 23 to 26 above)...

2019-03-01 19:36 UTC, icalderontt commented on lib/utils.js
> +  }
whoops. Good find. I fixed it

2019-03-01 19:41 UTC, icalderontt commented on .nvmrc
> +8.15.0
I removed it based on your comments. With my previous employer we always committed the .nvmrc file so that the next dev would know what version they are supposed to be running so I'm just used to committing it :D

2019-03-01 23:24 UTC, cmerchant commented
Please make sure you guys are updating the the version in package.json file. The last PR for vnext branch did not include an update to the version.

2019-03-05 15:30 UTC, privard requested changes

2019-03-05 15:30 UTC, privard commented on lib/utils.js
> +module.exports.getHTTPAgent = (function () {
This file seems to export only one thing, so why not call it getHTTPAgent.js instead of utils.js? Or even, connectionPool.js, or agentManager.js or something more scoped to its actual functionality?

2019-03-05 17:43 UTC, icalderontt commented on lib/utils.js
> +module.exports.getHTTPAgent = (function () {
Makes sense man. I just some changes I made based on your comment

2019-03-06 14:59 UTC, privard reviewed
The refactoring looks great. Before I approve, I think we need to check into how this is going to scale. I'm wondering how many connections a single agent can make, how how many requests per sec it can make on a single connection. We should definitely find a way to get numbers on this before we move this fix to production.

2019-03-06 14:59 UTC, privard approved these changes

2019-03-07 16:33 UTC, icalderontt commented
@privard: that a very valid concern. I couldn't find anything online regarding reusing agents and scaling problems. One thing that we could do if we found any issues is set the max number of allowed sockets in the agent to a # higher than 32. But I think that we should heavily test in dev first

2019-03-08 15:20 UTC, privard commented
Sounds good, merge at will

2019-03-08 15:23 UTC, merged