BMS-375: Add support for Brand API
PlayNetwork/playnetwork-sdk-nodejs pull request #90
Opened 2019-11-05 20:43 UTC by benjamin-morin

http://jira.touchtunes.com/browse/BMS-375

Only a few GET endpoints were implemented for now.

2019-11-05 22:17 UTC, badaldesai requested changes

2019-11-05 22:17 UTC, badaldesai commented on lib/brand.js
> +var
Can we use `const` :)

2019-11-05 22:17 UTC, badaldesai commented on lib/brand.js
> +	DEFAULT_HOST = 'master-brandapi.scaffold-workers-main-us.m.cld.octavelive.com',
We need to point to `develop` as default

2019-11-06 18:21 UTC, badaldesai approved these changes

2019-11-06 18:27 UTC, Mig-OG approved these changes
Look good to me.

2019-11-06 22:01 UTC, badaldesai commented on lib/brand.js
> +const DEFAULT_HOST = 'master-brand-api.apps.playnetwork.com';
Can we change it back to develop?

2019-11-07 12:33 UTC, gcerrott commented on lib/brand.js
> +const DEFAULT_HOST = 'master-brand-api.apps.playnetwork.com';
After review, it looks like all supported services by the SDK have the _master_ host as a default.  From a SDK client's perspective, the SDK configuration becomes inconsistent.
So, I have suggested to Benjamin that I puts back the _master_ host name for the sake of a consistent developer experience.

2019-11-07 12:35 UTC, gcerrott approved these changes

2019-11-14 21:06 UTC, benjamin-morin commented
Any update on this guys?

2019-11-15 13:21 UTC, merged