BMS-448: Added backoff mechanism when totalTimeout is supplied as settings
PlayNetwork/playnetwork-sdk-nodejs pull request #93
Opened 2020-01-09 15:26 UTC by badaldesai

2020-01-09 17:04 UTC, pmaudet commented on history.md
> +# v2.2.5 - 2020/01/08
v2.2.6

2020-01-09 17:31 UTC, Mig-OG requested changes

2020-01-09 17:31 UTC, Mig-OG commented on test/lib/request.js
> +	describe('request methods', () => {
From the mocha documentation, it is discourage to use arrow function. https://mochajs.org/#arrow-function

2020-01-09 23:00 UTC, badaldesai commented on test/lib/request.js
> +	describe('request methods', () => {
True, but there are all test using arrow function. That is fine. So, i did corrected new test but leave old one as it is.

2020-01-10 16:30 UTC, Mig-OG approved these changes

2020-01-24 15:52 UTC, pmaudet commented on lib/request.js
> +											.then(() => {
delay.then(makeRequest) no need to wrap it in a function.

2020-01-24 15:53 UTC, pmaudet approved these changes
Looks good, only a minor comment

2020-01-24 19:52 UTC, akobyshchatt commented on lib/request.js
> +	EXPONENT = 10,
I would rather double each subsequent delay instead of multiplying it by 10. How did you come up with this factor value?

2020-01-24 20:06 UTC, badaldesai commented on lib/request.js
> +	EXPONENT = 10,
Ok, i can do double. I just thought it would be better to wait for 1, 10, 100 than 1,2,4 which are basically making calls quite not improve that much. If you think it is better to double, i can change it to 2.

2020-01-24 20:19 UTC, akobyshchatt commented on lib/request.js
> +	EXPONENT = 10,
exponential backoff usually implies doubling the delay, if i'm not mistaken. 1 ms initial delay is probably too short. i would start with 10-30 ms.
if the remote endpoint is overloaded, doing fast retries will make it even worse.

2020-01-24 20:25 UTC, badaldesai commented on lib/request.js
> +	EXPONENT = 10,
Ok i added 30ms initial delay and change exponent to 2.

2020-01-24 21:16 UTC, akobyshchatt commented on lib/request.js
> +						options.initialDelay = 30;
should it be a constant?

2020-01-24 23:15 UTC, badaldesai commented on lib/request.js
> +						options.initialDelay = 30;
Added

2020-01-28 22:34 UTC, akobyshchatt approved these changes

2020-01-28 22:34 UTC, merged