BMS-370: Add ability to get profile based on authentication headers
PlayNetwork/playnetwork-sdk-nodejs pull request #94
Opened 2020-01-13 15:52 UTC by vartanbeno

[BMS-370](https://jira.touchtunes.com/browse/BMS-370)

2020-01-13 16:11 UTC, badaldesai requested changes

2020-01-13 16:11 UTC, badaldesai commented on test/lib/provision.js
> +		it('should properly retrieve profile even without profileAlias', (done) => {
Not sure, what is being tested here. If it is same as next test, this one might be removed.

2020-01-13 16:21 UTC, vartanbeno commented on test/lib/provision.js
> +		it('should properly retrieve profile even without profileAlias', (done) => {
Oh, there's a test for the promise-based result and the callback-based one.

2020-01-13 19:56 UTC, Mig-OG requested changes

2020-01-13 19:56 UTC, Mig-OG commented on test/lib/provision.js
> +		it('should properly retrieve profile even without profileAlias', (done) => {
From mocha documentation, it is discourage to use arrow function. https://mochajs.org/#arrow-functions. I know there is a lot of test written that way, but let's not add some. Please change from arrow function to old style lambda: `function() {}`

2020-01-13 19:56 UTC, Mig-OG commented on test/lib/provision.js
> +		it('should properly retrieve profile even without profileAlias (callback)', (done) => {
arrow function to old style lambda

2020-01-13 20:00 UTC, vartanbeno commented on test/lib/provision.js
> +		it('should properly retrieve profile even without profileAlias (callback)', (done) => {
Done

2020-01-14 16:01 UTC, badaldesai approved these changes

2020-01-14 16:34 UTC, Mig-OG approved these changes

2020-01-14 21:00 UTC, akobyshchatt approved these changes

2020-01-14 21:00 UTC, merged